# Generated by Django 5.2.8 on 2025-11-11 00:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(db_column='slug', max_length=150, unique=True, verbose_name='URL amigable')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categories',
                'indexes': [models.Index(fields=['slug'], name='idx_category_slug')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(db_column='slug', max_length=200, unique=True, verbose_name='URL amigable')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Descripción')),
                ('price', models.PositiveIntegerField(db_column='price', verbose_name='Precio')),
                ('discount_price', models.IntegerField(blank=True, db_column='discount_price', help_text='Precio final después del descuento en pesos chilenos (CLP, sin decimales). Si está configurado, se usa este precio directamente. Ejemplo: 22990', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio final del descuento')),
                ('discount_amount', models.IntegerField(blank=True, db_column='discount_amount', help_text='Monto fijo a descontar del precio en pesos chilenos (CLP, sin decimales). Ejemplo: si el precio es $100000 y aquí pones $20000, el precio final será $80000.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto a descontar')),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, db_column='discount_percent', help_text='Porcentaje de descuento. Ingresa solo un número entero entre 1 y 100 (ej: 20 para 20%, 25 para 25%). No se aceptan decimales.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento por porcentaje (%)')),
                ('stock_qty', models.PositiveIntegerField(db_column='stock_qty', default=0, verbose_name='Cantidad en stock')),
                ('brand', models.CharField(blank=True, db_column='brand', max_length=100, null=True, verbose_name='Marca')),
                ('sku', models.CharField(db_column='sku', max_length=64, unique=True, verbose_name='SKU')),
                ('active', models.BooleanField(db_column='active', default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Actualizado el')),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('url', models.CharField(db_column='url', max_length=500, verbose_name='URL')),
                ('alt_text', models.CharField(blank=True, db_column='alt_text', max_length=255, null=True, verbose_name='Texto alternativo')),
                ('position', models.PositiveIntegerField(db_column='position', default=0, verbose_name='Posición')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'db_table': 'product_images',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='idx_product_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='idx_product_slug'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active'], name='idx_product_active'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='idx_product_price'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_qty'], name='idx_product_stock'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'position'], name='idx_product_position'),
        ),
    ]
