# Generated by Django 5.2.7 on 2025-11-01 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('slug', models.SlugField(db_column='slug', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'indexes': [models.Index(fields=['slug'], name='idx_category_slug')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('slug', models.SlugField(db_column='slug', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
                ('stock_qty', models.PositiveIntegerField(db_column='stock_qty', default=0)),
                ('brand', models.CharField(blank=True, db_column='brand', max_length=100, null=True)),
                ('sku', models.CharField(db_column='sku', max_length=64, unique=True)),
                ('active', models.BooleanField(db_column='active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('url', models.CharField(db_column='url', max_length=500)),
                ('alt_text', models.CharField(blank=True, db_column='alt_text', max_length=255, null=True)),
                ('position', models.PositiveIntegerField(db_column='position', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='idx_product_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='idx_product_slug'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active'], name='idx_product_active'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='idx_product_price'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_qty'], name='idx_product_stock'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'position'], name='idx_product_position'),
        ),
    ]
