# Generated by Django 5.2.8 on 2025-11-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, db_column='image', help_text='Imagen representativa de la categoría. Se recomienda formato cuadrado (por ejemplo 600x600).', null=True, upload_to='categorias/', verbose_name='Imagen'),
        ),
    ]
