# Generated by Django 5.2.7 on 2025-11-05 21:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_discount_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position'], 'verbose_name': 'Imagen de Producto', 'verbose_name_plural': 'Imágenes de Producto'},
        ),
        migrations.AddField(
            model_name='product',
            name='discount_amount',
            field=models.DecimalField(blank=True, db_column='discount_amount', decimal_places=2, help_text='Monto fijo a descontar del precio. Ejemplo: si el precio es $100 y aquí pones $20, el precio final será $80.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto a descontar'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(blank=True, db_column='discount_percent', decimal_places=2, help_text='Porcentaje de descuento. Ingresa solo el número (ej: 20 para 20%, 25.5 para 25.5%).', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Descuento por porcentaje (%)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, db_column='description', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='name', max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(db_column='slug', max_length=150, unique=True, verbose_name='URL amigable'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(db_column='active', default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, db_column='brand', max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, db_column='description', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, db_column='discount_price', decimal_places=2, help_text='Precio final después del descuento. Si está configurado, se usa este precio directamente.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio final del descuento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_column='name', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_column='sku', max_length=64, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(db_column='slug', max_length=200, unique=True, verbose_name='URL amigable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.PositiveIntegerField(db_column='stock_qty', default=0, verbose_name='Cantidad en stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, db_column='alt_text', max_length=255, null=True, verbose_name='Texto alternativo'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='position',
            field=models.PositiveIntegerField(db_column='position', default=0, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.CharField(db_column='url', max_length=500, verbose_name='URL'),
        ),
    ]
