# Generated by Django 5.2.8 on 2025-11-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_idx_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_amount',
            field=models.PositiveIntegerField(blank=True, db_column='discount_amount', help_text='Monto fijo a descontar del precio en pesos chilenos (CLP, sin decimales). Ejemplo: si el precio es $100000 y aquí pones $20000, el precio final será $80000.', null=True, verbose_name='Monto a descontar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, db_column='discount_percent', help_text='Porcentaje de descuento. Ingresa un número entero entre 0 y 100 (ej: 20 para 20%).', null=True, verbose_name='Descuento por porcentaje (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(blank=True, db_column='discount_price', help_text='Precio final después del descuento en pesos chilenos (CLP, sin decimales). Si está configurado, se usa este precio directamente. Ejemplo: 22990', null=True, verbose_name='Precio final del descuento'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__isnull', True), models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), _connector='OR'), name='pct_range_0_100'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_price__isnull', False), ('discount_amount__isnull', False)), models.Q(('discount_price__isnull', False), ('discount_percent__isnull', False)), models.Q(('discount_amount__isnull', False), ('discount_percent__isnull', False)), _connector='OR', _negated=True), name='only_one_discount_mode'),
        ),
    ]
