# Generated by Django 5.2.7 on 2025-11-05 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_discount_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_amount',
            field=models.IntegerField(blank=True, db_column='discount_amount', help_text='Monto fijo a descontar del precio en pesos chilenos (CLP, sin decimales). Ejemplo: si el precio es $100000 y aquí pones $20000, el precio final será $80000.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto a descontar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, db_column='discount_percent', help_text='Porcentaje de descuento. Ingresa solo un número entero entre 1 y 100 (ej: 20 para 20%, 25 para 25%). No se aceptan decimales.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento por porcentaje (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, db_column='discount_price', help_text='Precio final después del descuento en pesos chilenos (CLP, sin decimales). Si está configurado, se usa este precio directamente. Ejemplo: 22990', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio final del descuento'),
        ),
    ]
