# Generated by Django 5.2.8 on 2025-11-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active', '-created_at'], name='idx_product_active_created'),
        ),
    ]
