# Generated by Django 5.2.8 on 2025-11-14 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_idx_product_active_created'),
    ]

    operations = [
        # 1. Agregar campo parent_category (nullable para migración)
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, db_column='parent_category_id', help_text='Categoría padre para crear jerarquías (ej: "Electrónica" > "Audio" > "Auriculares")', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='Categoría padre'),
        ),
        # 2. Eliminar constraint único anterior de name (si existe)
        # Django maneja esto automáticamente con AlterField, pero lo hacemos explícito
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='name', max_length=100, verbose_name='Nombre'),
        ),
        # 3. Agregar índice para parent_category
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent_category'], name='idx_category_parent'),
        ),
        # 4. Agregar constraint único compuesto (name + parent_category)
        # Esto permite nombres duplicados si tienen diferentes padres
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'parent_category'), name='uq_category_name_parent'),
        ),
    ]
