# Generated by Django 5.2.8 on 2025-11-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_add_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
