# Generated by Django 5.2.8 on 2025-11-30 00:45

from django.db import migrations


def add_gin_index_for_description(apps, schema_editor):
    """
    Crea índice GIN con pg_trgm para búsqueda de texto en description.
    Solo para PostgreSQL, ya que requiere la extensión pg_trgm.
    Optimiza queries con ILIKE/LIKE en el campo description.
    """
    db_vendor = schema_editor.connection.vendor
    
    if db_vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Verificar si el índice ya existe
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename = 'products' AND indexname = 'idx_product_description_trgm'
            """)
            index_exists = cursor.fetchone() is not None
            
            if not index_exists:
                # Habilitar extensión pg_trgm si no está habilitada
                try:
                    cursor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
                except Exception:
                    pass  # La extensión puede ya estar habilitada
                
                # Crear índice GIN
                cursor.execute("""
                    CREATE INDEX idx_product_description_trgm 
                    ON products USING gin (description gin_trgm_ops);
                """)


def remove_gin_index_for_description(apps, schema_editor):
    """Elimina el índice GIN de description"""
    db_vendor = schema_editor.connection.vendor
    
    if db_vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("DROP INDEX IF EXISTS idx_product_description_trgm;")


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_inventorymovement_id_and_more'),
    ]

    operations = [
        migrations.RunPython(
            add_gin_index_for_description,
            reverse_code=remove_gin_index_for_description
        ),
    ]
