# Generated by Django 5.2.8 on 2025-11-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('session_token', models.CharField(blank=True, db_column='session_token', max_length=100, null=True, unique=True, verbose_name='Token de sesión')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(db_column='quantity', verbose_name='Cantidad')),
                ('unit_price', models.PositiveIntegerField(db_column='unit_price', verbose_name='Precio unitario')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Item de Carrito',
                'verbose_name_plural': 'Items de Carrito',
                'db_table': 'cart_items',
            },
        ),
    ]
