# Generated by Django 5.2.8 on 2025-11-12 00:47

from django.db import migrations, models


def _round_half_up(value) -> int:
    if value is None:
        return 0
    value_str = str(value)
    if '.' in value_str:
        integer_part, fractional_part = value_str.split('.', 1)
    else:
        integer_part, fractional_part = value_str, ''
    fractional_part = (fractional_part + '00')[:2]
    rounded = int(integer_part or '0')
    if int(fractional_part) >= 50:
        rounded += 1
    return rounded


def normalize_cart_items(apps, schema_editor):
    CartItem = apps.get_model('cart', 'CartItem')
    for item in CartItem.objects.all().only('id', 'unit_price', 'quantity', 'total_price'):
        unit = _round_half_up(item.unit_price)
        quantity = int(getattr(item, 'quantity', 0) or 0)
        total = unit * quantity
        updates = {}
        if item.unit_price != unit:
            updates['unit_price'] = unit
        if getattr(item, 'total_price', None) != total:
            updates['total_price'] = total
        if updates:
            CartItem.objects.filter(pk=item.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('products', '0003_product_idx_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.PositiveIntegerField(db_column='total_price', default=0, verbose_name='Precio total'),
            preserve_default=False,
        ),
        migrations.RunPython(normalize_cart_items, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_price',
            field=models.PositiveIntegerField(db_column='unit_price', verbose_name='Precio unitario'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='idx_cartitem_cart_product'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product'], name='idx_cartitem_product'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='uq_cartitem_cart_product'),
        ),
    ]
