# Generated by Django 5.2.8 on 2025-11-30 00:46

from django.db import migrations


def add_session_token_partial_index(apps, schema_editor):
    """
    Crea índice parcial compuesto para carritos de invitados (session_token).
    Optimiza queries: filter(session_token=token, is_active=True).order_by('-created_at')
    
    Solo crea el índice si no existe y solo en PostgreSQL (soporta índices parciales).
    """
    db_vendor = schema_editor.connection.vendor
    
    if db_vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Verificar si el índice ya existe
            cursor.execute("""
                SELECT indexname FROM pg_indexes 
                WHERE tablename = 'carts' AND indexname = 'idx_cart_active_session'
            """)
            index_exists = cursor.fetchone() is not None
            
            if not index_exists:
                # Crear índice parcial compuesto
                cursor.execute("""
                    CREATE INDEX idx_cart_active_session 
                    ON carts (session_token, created_at) 
                    WHERE is_active = true AND session_token IS NOT NULL;
                """)


def remove_session_token_partial_index(apps, schema_editor):
    """Elimina el índice parcial de session_token"""
    db_vendor = schema_editor.connection.vendor
    
    if db_vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("DROP INDEX IF EXISTS idx_cart_active_session;")


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_ensure_cart_indexes'),
    ]

    operations = [
        migrations.RunPython(
            add_session_token_partial_index,
            reverse_code=remove_session_token_partial_index
        ),
    ]
