# Generated by Django 5.2.8 on 2025-12-01 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_add_session_token_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'is_active'], name='idx_cart_user_active'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_token', 'is_active'], name='idx_cart_session_active'),
        ),
    ]
