# Generated by Django 5.2.8 on 2025-11-28 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_fix_description_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herocarouselslide',
            name='alt_text',
            field=models.CharField(db_column='alt_text', help_text='Texto alternativo para accesibilidad (usado como alt de la imagen)', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Texto alternativo'),
        ),
        migrations.AlterField(
            model_name='herocarouselslide',
            name='image',
            field=models.ImageField(db_column='image', help_text='Imagen del slide. Se recomienda formato 1920x480px o similar (relación 4:1). Máximo 5MB.', upload_to='hero_carousel/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Imagen'),
        ),
    ]
