# Generated by Django 5.2.8 on 2025-11-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_herocarouselslide_alt_text_and_more'),
    ]

    operations = [
        # ✅ Índice compuesto mejorado que cubre filter(is_active=True).order_by('order', 'created_at')
        # El índice existente idx_hero_slide_active_order solo cubre (is_active, order)
        # Este nuevo índice incluye created_at para optimizar el ordenamiento completo
        migrations.AddIndex(
            model_name='herocarouselslide',
            index=models.Index(
                fields=['is_active', 'order', 'created_at'],
                name='idx_hero_slide_active_order_created'
            ),
        ),
    ]
