# Generated by Django 5.2.8 on 2025-12-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_add_hero_carousel_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='herocarouselslide',
            name='idx_hero_slide_active_order_created',
        ),
    ]
