# Generated by Django 5.2.7 on 2025-11-01 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=100)),
                ('last_name', models.CharField(db_column='last_name', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=50, null=True)),
                ('password_hash', models.CharField(db_column='password_hash', editable=False, max_length=255)),
                ('role', models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Admin')], db_column='role', default='cliente', max_length=20)),
                ('street', models.CharField(blank=True, db_column='street', max_length=200, null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=100, null=True)),
                ('region', models.CharField(blank=True, db_column='region', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, db_column='postal_code', max_length=20, null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['email'], name='idx_email'), models.Index(fields=['role'], name='idx_role')],
            },
        ),
    ]
