# Generated by Django 5.2.8 on 2025-11-11 00:03

import apps.users.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, db_column='username', max_length=150, null=True)),
                ('email', models.EmailField(db_column='email', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico')),
                ('role', models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Admin')], db_column='role', default='cliente', max_length=10, verbose_name='Rol')),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=50, null=True, verbose_name='Teléfono')),
                ('street', models.CharField(blank=True, db_column='street', max_length=200, null=True, verbose_name='Calle')),
                ('city', models.CharField(blank=True, db_column='city', max_length=100, null=True, verbose_name='Ciudad')),
                ('region', models.CharField(blank=True, db_column='region', max_length=100, null=True, verbose_name='Región')),
                ('postal_code', models.CharField(blank=True, db_column='postal_code', max_length=20, null=True, verbose_name='Código postal')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Actualizado el')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, db_column='label', help_text='Nombre descriptivo para esta dirección (ej: "Casa", "Oficina")', max_length=100, null=True, verbose_name='Etiqueta')),
                ('street', models.CharField(db_column='street', max_length=200, verbose_name='Calle')),
                ('number', models.CharField(blank=True, db_column='number', max_length=20, null=True, verbose_name='Número')),
                ('apartment', models.CharField(blank=True, db_column='apartment', help_text='Dpto/Casa/Oficina', max_length=100, null=True, verbose_name='Dpto/Casa/Oficina')),
                ('city', models.CharField(db_column='city', max_length=100, verbose_name='Comuna')),
                ('region', models.CharField(db_column='region', max_length=100, verbose_name='Región')),
                ('postal_code', models.CharField(blank=True, db_column='postal_code', max_length=20, null=True, verbose_name='Código postal')),
                ('is_default', models.BooleanField(db_column='is_default', default=False, help_text='Marcar como dirección predeterminada', verbose_name='Predeterminada')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Actualizado el')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'user_addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_column='token', default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el')),
                ('expires_at', models.DateTimeField(db_column='expires_at', default=apps.users.models._default_reset_expiration, verbose_name='Expira el')),
                ('used_at', models.DateTimeField(blank=True, db_column='used_at', null=True, verbose_name='Usado el')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Token de Restablecimiento de Contraseña',
                'verbose_name_plural': 'Tokens de Restablecimiento de Contraseña',
                'db_table': 'password_reset_tokens',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='idx_role'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user'], name='idx_address_user'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'is_default'], name='idx_address_user_default'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['expires_at'], name='idx_password_reset_expires'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'used_at'], name='idx_pwreset_user_used_at'),
        ),
    ]
