# Generated by Django 5.2.7 on 2025-11-05 23:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'verbose_name': 'Token de Restablecimiento de Contraseña', 'verbose_name_plural': 'Tokens de Restablecimiento de Contraseña'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(db_column='expires_at', verbose_name='Expira el'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(db_column='token', max_length=64, unique=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='used',
            field=models.BooleanField(db_column='used', default=False, verbose_name='Usado'),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, db_column='city', max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_column='email', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_column='phone', max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, db_column='postal_code', max_length=20, null=True, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, db_column='region', max_length=100, null=True, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Admin')], db_column='role', default='cliente', max_length=10, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, db_column='street', max_length=200, null=True, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Actualizado el'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, db_column='label', help_text='Nombre descriptivo para esta dirección (ej: "Casa", "Oficina")', max_length=100, null=True, verbose_name='Etiqueta')),
                ('street', models.CharField(db_column='street', max_length=200, verbose_name='Calle')),
                ('number', models.CharField(blank=True, db_column='number', max_length=20, null=True, verbose_name='Número')),
                ('apartment', models.CharField(blank=True, db_column='apartment', help_text='Dpto/Casa/Oficina', max_length=100, null=True, verbose_name='Dpto/Casa/Oficina')),
                ('city', models.CharField(db_column='city', max_length=100, verbose_name='Comuna')),
                ('region', models.CharField(db_column='region', max_length=100, verbose_name='Región')),
                ('postal_code', models.CharField(blank=True, db_column='postal_code', max_length=20, null=True, verbose_name='Código postal')),
                ('is_default', models.BooleanField(db_column='is_default', default=False, help_text='Marcar como dirección predeterminada', verbose_name='Predeterminada')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Actualizado el')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'user_addresses',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user'], name='idx_address_user'), models.Index(fields=['user', 'is_default'], name='idx_address_user_default')],
            },
        ),
    ]
