# Generated by Django 5.2.8 on 2025-11-08 23:47

import uuid

import apps.users.models
from django.db import migrations, models


def migrate_existing_tokens(apps, schema_editor):
    PasswordResetToken = apps.get_model('users', 'PasswordResetToken')
    for item in PasswordResetToken.objects.all():
        item.token = uuid.uuid4().hex
        item.save(update_fields=['token'])


def drop_used_column(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SHOW COLUMNS FROM password_reset_tokens LIKE 'used'")
        if cursor.fetchone():
            cursor.execute("ALTER TABLE password_reset_tokens DROP COLUMN used")


def add_used_column(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SHOW COLUMNS FROM password_reset_tokens LIKE 'used'")
        if not cursor.fetchone():
            cursor.execute("ALTER TABLE password_reset_tokens ADD COLUMN used TINYINT(1) DEFAULT 0")


def add_used_at_column(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SHOW COLUMNS FROM password_reset_tokens LIKE 'used_at'")
        if not cursor.fetchone():
            cursor.execute("ALTER TABLE password_reset_tokens ADD COLUMN used_at DATETIME NULL")


def remove_used_at_column(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SHOW COLUMNS FROM password_reset_tokens LIKE 'used_at'")
        if cursor.fetchone():
            cursor.execute("ALTER TABLE password_reset_tokens DROP COLUMN used_at")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_address_model'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_used_column, add_used_column)
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='passwordresettoken',
                    name='used',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_used_at_column, remove_used_at_column)
            ],
            state_operations=[
                migrations.AddField(
                    model_name='passwordresettoken',
                    name='used_at',
                    field=models.DateTimeField(blank=True, db_column='used_at', null=True, verbose_name='Usado el'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(db_column='expires_at', default=apps.users.models._default_reset_expiration, verbose_name='Expira el'),
        ),
        migrations.RunPython(migrate_existing_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.UUIDField(db_column='token', default=uuid.uuid4, editable=False, unique=True, verbose_name='Token'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['expires_at'], name='idx_reset_expires'),
        ),
    ]
