# Generated by Django 5.2.7 on 2025-11-01 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('action', models.CharField(db_column='action', max_length=100)),
                ('table_name', models.CharField(db_column='table_name', max_length=50)),
                ('record_id', models.BigIntegerField(blank=True, db_column='record_id', null=True)),
                ('old_values', models.JSONField(blank=True, db_column='old_values', null=True)),
                ('new_values', models.JSONField(blank=True, db_column='new_values', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_column='ip_address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='idx_audit_user'), models.Index(fields=['table_name'], name='idx_audit_table'), models.Index(fields=['created_at'], name='idx_audit_created')],
            },
        ),
    ]
