# Generated by Django 5.2.8 on 2025-11-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('action', models.CharField(db_column='action', max_length=100, verbose_name='Acción')),
                ('table_name', models.CharField(db_column='table_name', max_length=50, verbose_name='Nombre de tabla')),
                ('record_id', models.BigIntegerField(blank=True, db_column='record_id', null=True, verbose_name='ID del registro')),
                ('old_values', models.JSONField(blank=True, db_column='old_values', null=True, verbose_name='Valores anteriores')),
                ('new_values', models.JSONField(blank=True, db_column='new_values', null=True, verbose_name='Valores nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_column='ip_address', null=True, verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
