# Generated by Django 5.2.7 on 2025-11-01 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='code', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Order Statuses',
                'db_table': 'order_statuses',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='code', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Statuses',
                'db_table': 'payment_statuses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(db_column='customer_name', max_length=200)),
                ('customer_email', models.EmailField(db_column='customer_email', max_length=255)),
                ('customer_phone', models.CharField(blank=True, db_column='customer_phone', max_length=50, null=True)),
                ('shipping_street', models.CharField(db_column='shipping_street', max_length=200)),
                ('shipping_city', models.CharField(db_column='shipping_city', max_length=100)),
                ('shipping_region', models.CharField(db_column='shipping_region', max_length=100)),
                ('shipping_postal_code', models.CharField(blank=True, db_column='shipping_postal_code', max_length=20, null=True)),
                ('total_amount', models.DecimalField(db_column='total_amount', decimal_places=2, max_digits=10)),
                ('shipping_cost', models.DecimalField(db_column='shipping_cost', decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(db_column='currency', default='CLP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='orders.orderstatus')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(db_column='quantity')),
                ('unit_price', models.DecimalField(db_column='unit_price', decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(db_column='total_price', decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='products.product')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_column='changed_at')),
                ('note', models.CharField(blank=True, db_column='note', max_length=255, null=True)),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.RESTRICT, related_name='history_entries', to='orders.orderstatus')),
            ],
            options={
                'verbose_name_plural': 'Order Status History',
                'db_table': 'order_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('payment_method', models.CharField(db_column='payment_method', default='webpay', max_length=50)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=10)),
                ('currency', models.CharField(db_column='currency', default='CLP', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='orders.paymentstatus')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('tbk_token', models.CharField(db_column='tbk_token', max_length=200, unique=True)),
                ('buy_order', models.CharField(db_column='buy_order', max_length=64, unique=True)),
                ('session_id', models.CharField(db_column='session_id', max_length=64)),
                ('authorization_code', models.CharField(blank=True, db_column='authorization_code', max_length=64, null=True)),
                ('response_code', models.IntegerField(blank=True, db_column='response_code', null=True)),
                ('card_detail', models.CharField(blank=True, db_column='card_detail', max_length=100, null=True)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=10)),
                ('status', models.CharField(blank=True, db_column='status', max_length=50, null=True)),
                ('processed_at', models.DateTimeField(blank=True, db_column='processed_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('payment', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.payment')),
            ],
            options={
                'db_table': 'payment_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='idx_orders_user'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='idx_orders_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='idx_orders_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='idx_orders_user_created'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['tbk_token'], name='idx_token'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['buy_order'], name='idx_buy_order'),
        ),
    ]
