# Generated by Django 5.2.8 on 2025-11-11 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(db_column='customer_name', max_length=200, verbose_name='Nombre del cliente')),
                ('customer_email', models.EmailField(db_column='customer_email', max_length=255, verbose_name='Correo del cliente')),
                ('customer_phone', models.CharField(blank=True, db_column='customer_phone', max_length=50, null=True, verbose_name='Teléfono del cliente')),
                ('shipping_street', models.CharField(db_column='shipping_street', max_length=200, verbose_name='Calle de envío')),
                ('shipping_city', models.CharField(db_column='shipping_city', max_length=100, verbose_name='Ciudad de envío')),
                ('shipping_region', models.CharField(db_column='shipping_region', max_length=100, verbose_name='Región de envío')),
                ('shipping_postal_code', models.CharField(blank=True, db_column='shipping_postal_code', max_length=20, null=True, verbose_name='Código postal de envío')),
                ('total_amount', models.PositiveIntegerField(db_column='total_amount', verbose_name='Monto total')),
                ('shipping_cost', models.PositiveIntegerField(db_column='shipping_cost', default=0, verbose_name='Costo de envío')),
                ('currency', models.CharField(db_column='currency', default='CLP', max_length=10, verbose_name='Moneda')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(db_column='quantity', verbose_name='Cantidad')),
                ('unit_price', models.PositiveIntegerField(db_column='unit_price', verbose_name='Precio unitario')),
                ('total_price', models.PositiveIntegerField(db_column='total_price', verbose_name='Precio total')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='code', max_length=50, unique=True, verbose_name='Código')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado de Pedido',
                'verbose_name_plural': 'Estados de Pedido',
                'db_table': 'order_statuses',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_column='changed_at', verbose_name='Cambiado el')),
                ('note', models.CharField(blank=True, db_column='note', max_length=255, null=True, verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Pedido',
                'verbose_name_plural': 'Historial de Estados de Pedido',
                'db_table': 'order_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('payment_method', models.CharField(db_column='payment_method', default='webpay', max_length=50, verbose_name='Método de pago')),
                ('amount', models.PositiveIntegerField(db_column='amount', verbose_name='Monto', null=True, blank=True)),
                ('currency', models.CharField(db_column='currency', default='CLP', max_length=10, verbose_name='Moneda')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='code', max_length=50, unique=True, verbose_name='Código')),
                ('description', models.CharField(blank=True, db_column='description', max_length=255, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado de Pago',
                'verbose_name_plural': 'Estados de Pago',
                'db_table': 'payment_statuses',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('tbk_token', models.CharField(db_column='tbk_token', max_length=200, unique=True, verbose_name='Token TBK')),
                ('buy_order', models.CharField(db_column='buy_order', max_length=64, unique=True, verbose_name='Orden de compra')),
                ('session_id', models.CharField(db_column='session_id', max_length=64, verbose_name='ID de sesión')),
                ('authorization_code', models.CharField(blank=True, db_column='authorization_code', max_length=64, null=True, verbose_name='Código de autorización')),
                ('response_code', models.IntegerField(blank=True, db_column='response_code', null=True, verbose_name='Código de respuesta')),
                ('card_detail', models.CharField(blank=True, db_column='card_detail', max_length=100, null=True, verbose_name='Detalle de tarjeta')),
                ('amount', models.PositiveIntegerField(db_column='amount', verbose_name='Monto')),
                ('status', models.CharField(blank=True, db_column='status', max_length=50, null=True, verbose_name='Estado')),
                ('processed_at', models.DateTimeField(blank=True, db_column='processed_at', null=True, verbose_name='Procesado el')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
                'db_table': 'payment_transactions',
            },
        ),
        migrations.CreateModel(
            name='ShippingRule',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('PRODUCT', 'Producto específico'), ('CATEGORY', 'Categoría'), ('ALL', 'Todas las ventas')], db_column='rule_type', help_text='Tipo de regla: PRODUCT (producto), CATEGORY (categoría), ALL (todas)', max_length=20)),
                ('priority', models.IntegerField(db_column='priority', default=0, help_text='Prioridad (mayor número = mayor prioridad). Las reglas de PRODUCT tienen prioridad sobre CATEGORY, y CATEGORY sobre ALL.', validators=[django.core.validators.MinValueValidator(0)])),
                ('base_cost', models.PositiveIntegerField(db_column='base_cost', default=0, help_text='Costo base de envío')),
                ('free_shipping_threshold', models.PositiveIntegerField(blank=True, db_column='free_shipping_threshold', help_text='Umbral para envío gratis (null = no hay envío gratis para esta regla)', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Regla de Envío',
                'verbose_name_plural': 'Reglas de Envío',
                'db_table': 'shipping_rules',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('code', models.CharField(db_column='code', help_text='Código único de la zona (ej: REGION_METROPOLITANA)', max_length=50, unique=True)),
                ('regions', models.JSONField(db_column='regions', default=list, help_text='Lista de regiones incluidas en esta zona (ej: ["Región Metropolitana", "Santiago"])')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Zona de Envío',
                'verbose_name_plural': 'Zonas de Envío',
                'db_table': 'shipping_zones',
            },
        ),
    ]
