# Generated by Django 5.2.7 on 2025-11-05 18:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('code', models.CharField(db_column='code', help_text='Código único de la zona (ej: REGION_METROPOLITANA)', max_length=50, unique=True)),
                ('regions', models.JSONField(db_column='regions', default=list, help_text='Lista de regiones incluidas en esta zona (ej: ["Región Metropolitana", "Santiago"])')),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Zona de Envío',
                'verbose_name_plural': 'Zonas de Envío',
                'db_table': 'shipping_zones',
                'indexes': [models.Index(fields=['code'], name='idx_zone_code'), models.Index(fields=['is_active'], name='idx_zone_active')],
            },
        ),
        migrations.CreateModel(
            name='ShippingRule',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('PRODUCT', 'Producto específico'), ('CATEGORY', 'Categoría'), ('ALL', 'Todas las ventas')], db_column='rule_type', help_text='Tipo de regla: PRODUCT (producto), CATEGORY (categoría), ALL (todas)', max_length=20)),
                ('priority', models.IntegerField(db_column='priority', default=0, help_text='Prioridad (mayor número = mayor prioridad). Las reglas de PRODUCT tienen prioridad sobre CATEGORY, y CATEGORY sobre ALL.', validators=[django.core.validators.MinValueValidator(0)])),
                ('base_cost', models.DecimalField(db_column='base_cost', decimal_places=2, default=Decimal('0.00'), help_text='Costo base de envío', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('free_shipping_threshold', models.DecimalField(blank=True, db_column='free_shipping_threshold', decimal_places=2, help_text='Umbral para envío gratis (null = no hay envío gratis para esta regla)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('category', models.ForeignKey(blank=True, db_column='category_id', help_text='Categoría específica (solo si rule_type=CATEGORY)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rules', to='products.category')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', help_text='Producto específico (solo si rule_type=PRODUCT)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rules', to='products.product')),
                ('zone', models.ForeignKey(blank=True, db_column='zone_id', help_text='Si es null, aplica a todas las zonas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rules', to='orders.shippingzone')),
            ],
            options={
                'verbose_name': 'Regla de Envío',
                'verbose_name_plural': 'Reglas de Envío',
                'db_table': 'shipping_rules',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['zone', 'is_active'], name='idx_rule_zone_active'), models.Index(fields=['rule_type', 'is_active'], name='idx_rule_type_active'), models.Index(fields=['priority'], name='idx_rule_priority')],
            },
        ),
    ]
