# Generated by Django 5.2.8 on 2025-11-11 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='orders.orderstatus', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, db_column='changed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='status',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.RESTRICT, related_name='history_entries', to='orders.orderstatus', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='orders.paymentstatus', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment',
            field=models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.payment', verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='shippingrule',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', help_text='Categoría específica (solo si rule_type=CATEGORY)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rules', to='products.category'),
        ),
        migrations.AddField(
            model_name='shippingrule',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', help_text='Producto específico (solo si rule_type=PRODUCT)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rules', to='products.product'),
        ),
        migrations.AddIndex(
            model_name='shippingzone',
            index=models.Index(fields=['code'], name='idx_zone_code'),
        ),
        migrations.AddIndex(
            model_name='shippingzone',
            index=models.Index(fields=['is_active'], name='idx_zone_active'),
        ),
        migrations.AddField(
            model_name='shippingrule',
            name='zone',
            field=models.ForeignKey(blank=True, db_column='zone_id', help_text='Si es null, aplica a todas las zonas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rules', to='orders.shippingzone'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='idx_orders_user'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='idx_orders_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='idx_orders_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='idx_orders_user_created'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['tbk_token'], name='idx_token'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['buy_order'], name='idx_buy_order'),
        ),
        migrations.AddIndex(
            model_name='shippingrule',
            index=models.Index(fields=['zone', 'is_active'], name='idx_rule_zone_active'),
        ),
        migrations.AddIndex(
            model_name='shippingrule',
            index=models.Index(fields=['rule_type', 'is_active'], name='idx_rule_type_active'),
        ),
        migrations.AddIndex(
            model_name='shippingrule',
            index=models.Index(fields=['priority'], name='idx_rule_priority'),
        ),
    ]
