# Generated by Django 5.2.8 on 2025-11-12 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _round_half_up(value):
    if value is None:
        return 0
    value_str = str(value)
    if '.' in value_str:
        integer_part, fractional_part = value_str.split('.', 1)
    else:
        integer_part, fractional_part = value_str, ''
    fractional_part = (fractional_part + '00')[:2]
    rounded = int(integer_part or '0')
    if int(fractional_part) >= 50:
        rounded += 1
    return rounded


def round_orders_monetary_fields(apps, schema_editor):
    def round_value(value):
        if value is None:
            return None
        return _round_half_up(value)

    Order = apps.get_model('orders', 'Order')
    OrderItem = apps.get_model('orders', 'OrderItem')
    Payment = apps.get_model('orders', 'Payment')
    PaymentTransaction = apps.get_model('orders', 'PaymentTransaction')
    ShippingRule = apps.get_model('orders', 'ShippingRule')

    for order in Order.objects.all().only('id', 'total_amount', 'shipping_cost'):
        updated_fields = []
        rounded_total = round_value(getattr(order, 'total_amount', None))
        rounded_shipping = round_value(getattr(order, 'shipping_cost', None))
        if rounded_total is not None and order.total_amount != rounded_total:
            order.total_amount = rounded_total
            updated_fields.append('total_amount')
        if rounded_shipping is not None and order.shipping_cost != rounded_shipping:
            order.shipping_cost = rounded_shipping
            updated_fields.append('shipping_cost')
        if updated_fields:
            order.save(update_fields=updated_fields)

    for item in OrderItem.objects.all().only('id', 'unit_price', 'total_price'):
        updated_fields = []
        rounded_unit = round_value(getattr(item, 'unit_price', None))
        rounded_total = round_value(getattr(item, 'total_price', None))
        if rounded_unit is not None and item.unit_price != rounded_unit:
            item.unit_price = rounded_unit
            updated_fields.append('unit_price')
        if rounded_total is not None and item.total_price != rounded_total:
            item.total_price = rounded_total
            updated_fields.append('total_price')
        if updated_fields:
            item.save(update_fields=updated_fields)

    for payment in Payment.objects.all().only('id', 'amount'):
        rounded_amount = round_value(getattr(payment, 'amount', None))
        if rounded_amount is not None and payment.amount != rounded_amount:
            payment.amount = rounded_amount
            payment.save(update_fields=['amount'])

    for transaction in PaymentTransaction.objects.all().only('id', 'amount'):
        rounded_amount = round_value(getattr(transaction, 'amount', None))
        if rounded_amount is not None and transaction.amount != rounded_amount:
            transaction.amount = rounded_amount
            transaction.save(update_fields=['amount'])

    for rule in ShippingRule.objects.all().only('id', 'base_cost', 'free_shipping_threshold'):
        updated_fields = []
        rounded_cost = round_value(getattr(rule, 'base_cost', None))
        rounded_threshold = round_value(getattr(rule, 'free_shipping_threshold', None))
        if rounded_cost is not None and rule.base_cost != rounded_cost:
            rule.base_cost = rounded_cost
            updated_fields.append('base_cost')
        if rounded_threshold is not None and rule.free_shipping_threshold != rounded_threshold:
            rule.free_shipping_threshold = rounded_threshold
            updated_fields.append('free_shipping_threshold')
        if updated_fields:
            rule.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('products', '0003_product_idx_product_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='idx_payment_tx_token',
            old_name='idx_token',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='idx_payment_tx_buy_order',
            old_name='idx_buy_order',
        ),
        migrations.RunPython(round_orders_monetary_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.PositiveIntegerField(db_column='shipping_cost', default=0, verbose_name='Costo de envío'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.PositiveIntegerField(db_column='total_amount', verbose_name='Monto total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(db_column='total_price', verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.PositiveIntegerField(db_column='unit_price', verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(db_column='amount', verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.PositiveIntegerField(db_column='amount', verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='base_cost',
            field=models.PositiveIntegerField(db_column='base_cost', default=0, help_text='Costo base de envío', verbose_name='Costo base'),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', help_text='Categoría específica (solo si rule_type=CATEGORY)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rules', to='products.category', verbose_name='Categoría específica'),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='free_shipping_threshold',
            field=models.PositiveIntegerField(blank=True, db_column='free_shipping_threshold', help_text='Umbral para envío gratis (null = no hay envío gratis para esta regla)', null=True, verbose_name='Umbral de envío gratis'),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', help_text='Producto específico (solo si rule_type=PRODUCT)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rules', to='products.product', verbose_name='Producto específico'),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='zone',
            field=models.ForeignKey(blank=True, db_column='zone_id', help_text='Si es null, aplica a todas las zonas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rules', to='orders.shippingzone', verbose_name='Zona de envío'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='code',
            field=models.CharField(db_column='code', help_text='Código único de la zona (ej: REGION_METROPOLITANA)', max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='name',
            field=models.CharField(db_column='name', help_text='Etiqueta visible en el panel para identificar la zona de envío.', max_length=120, unique=True, verbose_name='Nombre de la zona'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='regions',
            field=models.JSONField(db_column='regions', default=list, help_text='Lista de regiones incluidas en esta zona (ej: ["Región Metropolitana", "Santiago"])', verbose_name='Regiones'),
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Actualizado el'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_email'], name='idx_order_customer_email'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['session_id'], name='idx_payment_tx_session'),
        ),
        migrations.AddIndex(
            model_name='shippingrule',
            index=models.Index(fields=['rule_type', 'product'], name='idx_shiprule_type_product'),
        ),
        migrations.AddIndex(
            model_name='shippingrule',
            index=models.Index(fields=['rule_type', 'category'], name='idx_shiprule_type_category'),
        ),
    ]
