# Generated by Django 5.2.8 on 2025-11-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_idx_token_idx_payment_tx_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(blank=True, db_column='amount', null=True, verbose_name='Monto'),
        ),
    ]
