# Generated by Django 5.2.8 on 2025-11-14 20:12

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_order_items(apps, schema_editor):
    """
    Crea snapshots para todos los OrderItem existentes.
    Usa los datos actuales del producto para crear el snapshot.
    """
    OrderItem = apps.get_model('orders', 'OrderItem')
    OrderItemSnapshot = apps.get_model('orders', 'OrderItemSnapshot')
    Product = apps.get_model('products', 'Product')
    
    # Obtener todos los items con su producto relacionado
    order_items = OrderItem.objects.select_related('product', 'product__category').all()
    
    if not order_items.exists():
        return  # No hay items, no hay nada que migrar
    
    for item in order_items:
        product = item.product
        
        # Obtener información del producto
        product_name = product.name if product else 'Producto eliminado'
        product_sku = product.sku if product and hasattr(product, 'sku') else ''
        product_id = product.id if product else None
        product_brand = product.brand if product and hasattr(product, 'brand') else None
        product_category_name = None
        
        # Obtener nombre de categoría si existe
        if product and hasattr(product, 'category') and product.category:
            product_category_name = product.category.name if hasattr(product.category, 'name') else None
        
        # Crear snapshot con los datos actuales
        snapshot = OrderItemSnapshot.objects.create(
            product_name=product_name,
            product_sku=product_sku,
            product_id=product_id,
            unit_price=item.unit_price,
            total_price=item.total_price,
            product_brand=product_brand,
            product_category_name=product_category_name,
        )
        
        # Vincular snapshot al item
        item.price_snapshot = snapshot
        item.save(update_fields=['price_snapshot'])


def reverse_migrate_order_items(apps, schema_editor):
    """
    Reversa la migración eliminando los snapshots.
    """
    OrderItemSnapshot = apps.get_model('orders', 'OrderItemSnapshot')
    OrderItemSnapshot.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_create_shipping_snapshots'),
        ('products', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershippingsnapshot',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='OrderItemSnapshot',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='product_name', max_length=200, verbose_name='Nombre del producto')),
                ('product_sku', models.CharField(db_column='product_sku', max_length=64, verbose_name='SKU del producto')),
                ('product_id', models.PositiveIntegerField(blank=True, db_column='product_id', help_text='Referencia al producto original (nullable si se elimina)', null=True, verbose_name='ID del producto original')),
                ('unit_price', models.PositiveIntegerField(db_column='unit_price', verbose_name='Precio unitario')),
                ('total_price', models.PositiveIntegerField(db_column='total_price', verbose_name='Precio total')),
                ('product_brand', models.CharField(blank=True, db_column='product_brand', max_length=100, null=True, verbose_name='Marca')),
                ('product_category_name', models.CharField(blank=True, db_column='product_category_name', max_length=200, null=True, verbose_name='Categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Snapshot de Item de Pedido',
                'verbose_name_plural': 'Snapshots de Items de Pedido',
                'db_table': 'order_item_snapshots',
                'indexes': [models.Index(fields=['created_at'], name='idx_item_snapshot_created'), models.Index(fields=['product_id'], name='idx_item_snapshot_product'), models.Index(fields=['product_sku'], name='idx_item_snapshot_sku')],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_snapshot',
            field=models.OneToOneField(blank=True, db_column='price_snapshot_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='orders.orderitemsnapshot', verbose_name='Snapshot de precio'),
        ),
        # Migrar datos existentes
        migrations.RunPython(
            migrate_existing_order_items,
            reverse_migrate_order_items,
        ),
    ]
