# Generated by Django 5.2.8 on 2025-11-14 21:23

import django.db.models.deletion
from django.db import migrations, models


def migrate_payment_amounts_to_transactions(apps, schema_editor):
    """
    Migrar amounts de Payment a PaymentTransaction.
    Si un Payment tiene amount pero no tiene transacciones, crear una transacción con ese monto.
    """
    Payment = apps.get_model('orders', 'Payment')
    PaymentTransaction = apps.get_model('orders', 'PaymentTransaction')
    import uuid
    
    for payment in Payment.objects.all():
        # Si el payment tiene amount pero no tiene transacciones, crear una
        if payment.amount and payment.amount > 0:
            # Verificar si ya tiene transacciones
            existing_tx = PaymentTransaction.objects.filter(payment_id=payment.id).first()
            if not existing_tx:
                # Generar valores únicos para tbk_token y buy_order
                unique_suffix = str(uuid.uuid4())[:8]
                tbk_token = f'migrated_{payment.id}_{unique_suffix}'
                buy_order = f'MIGRATED_{payment.id}_{unique_suffix}'
                
                # Asegurar que no existan (aunque es muy improbable)
                while PaymentTransaction.objects.filter(tbk_token=tbk_token).exists():
                    unique_suffix = str(uuid.uuid4())[:8]
                    tbk_token = f'migrated_{payment.id}_{unique_suffix}'
                while PaymentTransaction.objects.filter(buy_order=buy_order).exists():
                    unique_suffix = str(uuid.uuid4())[:8]
                    buy_order = f'MIGRATED_{payment.id}_{unique_suffix}'
                
                # Crear transacción con el monto del payment
                PaymentTransaction.objects.create(
                    payment_id=payment.id,
                    tbk_token=tbk_token,
                    buy_order=buy_order,
                    session_id=f'migrated_session_{payment.id}_{unique_suffix}',
                    amount=payment.amount,
                    status='approved' if payment.status and payment.status.code == 'approved' else 'pending',
                    processed_at=payment.created_at,
                    created_at=payment.created_at,
                    updated_at=payment.updated_at,
                )


def reverse_migrate_payment_amounts(apps, schema_editor):
    """
    Reversa: copiar amount de la transacción más reciente al Payment.
    """
    Payment = apps.get_model('orders', 'Payment')
    PaymentTransaction = apps.get_model('orders', 'PaymentTransaction')
    
    for payment in Payment.objects.all():
        # Buscar la transacción más reciente
        latest_tx = PaymentTransaction.objects.filter(payment_id=payment.id).order_by('-created_at').first()
        if latest_tx and latest_tx.amount:
            payment.amount = latest_tx.amount
            payment.save(update_fields=['amount'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_create_item_snapshots'),
    ]

    operations = [
        # 1. Migrar datos antes de eliminar el campo
        migrations.RunPython(
            migrate_payment_amounts_to_transactions,
            reverse_migrate_payment_amounts,
        ),
        # 2. Eliminar campo amount de Payment
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        # 3. Actualizar campo status con help_text
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(db_column='status_id', help_text='Estado del pago (sincronizado con la transacción actual)', on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='orders.paymentstatus', verbose_name='Estado'),
        ),
        # 4. Agregar índices
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='idx_payment_order'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='idx_payment_status'),
        ),
    ]
