# Generated by Django 5.2.8 on 2025-11-28 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_add_unique_constraint_webpay_buy_order'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='idx_payment_tx_token',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='idx_payment_tx_buy_order',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='idx_payment_tx_session',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shippingcarrier',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='base_cost',
            field=models.PositiveIntegerField(db_column='base_cost', help_text='Costo base del envío', verbose_name='Costo base'),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='free_shipping_threshold',
            field=models.PositiveIntegerField(blank=True, db_column='free_shipping_threshold', help_text='Monto para envío gratis. NULL = no aplica', null=True, verbose_name='Umbral de envío gratis'),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='priority',
            field=models.IntegerField(db_column='priority', default=0, help_text='Prioridad al evaluar múltiples reglas (mayor = más prioritario)', verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='zone',
            field=models.ForeignKey(blank=True, db_column='zone_id', help_text='Zona geográfica. NULL = aplica a todas las zonas', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='orders.shippingzone', verbose_name='Zona de envío'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['order'], name='idx_payment_tx_order'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='idx_payment_tx_status'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['webpay_token'], name='idx_payment_webpay_token'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='idx_payment_tx_created'),
        ),
        migrations.AddIndex(
            model_name='shippingrule',
            index=models.Index(fields=['-priority'], name='idx_rule_priority'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('webpay_buy_order__isnull', False)), fields=('webpay_buy_order',), name='idx_payment_buy_order_unique'),
        ),
    ]
