# Generated by Django 5.2.8 on 2025-11-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_paymenttransaction_idx_payment_tx_token_and_more'),
    ]

    operations = [
        # ✅ Índice compuesto para optimizar queries que filtran por order_id y status
        # Útil para: PaymentTransaction.objects.filter(order_id=order_id, status='pending')
        # Los índices simples idx_payment_tx_order y idx_payment_tx_status existen,
        # pero un índice compuesto mejora el rendimiento cuando se usan ambas columnas juntas
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(
                fields=['order', 'status'],
                name='idx_payment_tx_order_status'
            ),
        ),
    ]
