# Generated by Django 5.2.8 on 2025-12-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_add_payment_tx_composite_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='idx_payment_tx_order_status',
        ),
    ]
