# Generated by Django 5.2.8 on 2025-12-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_paymenttransaction_idx_payment_tx_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('webpay', 'Webpay (Tarjeta)'), ('transfer', 'Transferencia Bancaria'), ('cash', 'Efectivo (Retiro en tienda)')], db_column='payment_method', db_index=True, default='webpay', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], db_column='status', db_index=True, default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='idx_payment_status_created'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_method', '-created_at'], name='idx_payment_tx_method_created'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', '-created_at'], name='idx_payment_tx_status_created'),
        ),
    ]
